import type { ProvenanceStory } from "./types";

// The sample claim's origins-first provenance (#507), invented for the offline
// preview. Built by the API's own buildProvenanceStory from a small graph, so
// depth, counts and ordering are what the endpoint would serve. It exercises
// both kinds of origin (a primary kind, and a Steward-recorded underlying
// source), untraced sources, divergence, like siblings that merge, republished
// copies, and a layer deep enough to fold.
export const INFLATION_PROVENANCE: ProvenanceStory = {
  claim_id: "inflation-2022",
  nodes: [
    {source: {id: "src-bls", title: "Consumer Price Index — December 2022 (BLS)", url: "https://www.bls.gov/news.release/archives/cpi_01122023.htm", source_type: "official_statistics"}, instance_ids: ["inst-1"], underlying: false, standing: "origin", basis: "primary_source_kind", root: null, depth: 0, upstream: [], copy_of: [], downstream: 4, downstream_total: 15, copies: 0, diverges: false},
    {source: {id: "src-fomc", title: "Statement on Longer-Run Goals and Monetary Policy Strategy (FOMC)", url: "https://www.federalreserve.gov/monetarypolicy/files/FOMC_LongerRunGoals.pdf", source_type: "policy_document"}, instance_ids: [], underlying: true, standing: "origin", basis: "steward", root: {status: "origin", basis: "The Committee's own statement of its target; nothing earlier sets it.", created_by: "claim_steward", updated_at: "2025-08-30T14:00:00Z"}, depth: 0, upstream: [], copy_of: [], downstream: 2, downstream_total: 8, copies: 0, diverges: false},
    {source: {id: "src-podcast", title: "Episode 212: the year prices broke", url: null, source_type: "podcast"}, instance_ids: ["inst-p17"], underlying: false, standing: "untraced", basis: "steward", root: {status: "untraced", basis: "The episode names no source for its figure.", created_by: "claim_steward", updated_at: "2025-08-30T14:00:00Z"}, depth: 0, upstream: [], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-pfblog", title: "Why 2022 was the worst year for your wallet", url: null, source_type: "blog"}, instance_ids: ["inst-p16"], underlying: false, standing: "untraced", basis: "none", root: null, depth: 0, upstream: [], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-tank", title: "Inflation is back: the 2022 price shock", url: null, source_type: "think_tank_report"}, instance_ids: ["inst-p7"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 1, upstream: [{source_id: "src-bls", relation_type: "derives_from", fidelity: "strengthened"},{source_id: "src-fomc", relation_type: "cites_as_evidence", fidelity: "faithful"}], copy_of: [], downstream: 1, downstream_total: 6, copies: 0, diverges: true},
    {source: {id: "src-brief", title: "Policy brief: what counts as high inflation", url: null, source_type: "policy_brief"}, instance_ids: ["inst-p15"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 1, upstream: [{source_id: "src-fomc", relation_type: "cites_as_evidence", fidelity: "misattributed"}], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: true},
    {source: {id: "src-wire", title: "US inflation ends 2022 at 6.5%, down from its June peak", url: null, source_type: "news_wire"}, instance_ids: ["inst-p1"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 1, upstream: [{source_id: "src-bls", relation_type: "repeats", fidelity: "faithful"}], copy_of: [], downstream: 5, downstream_total: 5, copies: 5, diverges: false},
    {source: {id: "src-news", title: "A year of soaring prices, in charts", url: "https://example.com/2022-inflation-charts", source_type: "news_secondary"}, instance_ids: ["inst-2"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 1, upstream: [{source_id: "src-bls", relation_type: "derives_from", fidelity: "faithful"}], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-blog", title: "Core and headline CPI in 2022, recomputed", url: null, source_type: "blog"}, instance_ids: ["inst-p14"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 1, upstream: [{source_id: "src-bls", relation_type: "reanalyzes", fidelity: "faithful"}], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-oped", title: "Runaway prices and the cost of waiting", url: null, source_type: "opinion"}, instance_ids: ["inst-p8"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 2, upstream: [{source_id: "src-tank", relation_type: "repeats", fidelity: "strengthened"}], copy_of: [], downstream: 5, downstream_total: 5, copies: 0, diverges: true},
    {source: {id: "src-letter-1", title: "Morning markets newsletter, 13 January 2023", url: null, source_type: "newsletter"}, instance_ids: ["inst-p5"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 2, upstream: [{source_id: "src-wire", relation_type: "repeats", fidelity: "faithful"}], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-wire-c2", title: "US inflation ends 2022 at 6.5% (business portal)", url: null, source_type: "news_secondary"}, instance_ids: ["inst-p3"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 2, upstream: [], copy_of: ["src-wire"], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-wire-c3", title: "US inflation ends 2022 at 6.5% (radio site)", url: null, source_type: "news_secondary"}, instance_ids: ["inst-p4"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 2, upstream: [], copy_of: ["src-wire"], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-wire-c1", title: "US inflation ends 2022 at 6.5% (regional daily)", url: null, source_type: "news_secondary"}, instance_ids: ["inst-p2"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 2, upstream: [], copy_of: ["src-wire"], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-letter-2", title: "Weekly money digest, 15 January 2023", url: null, source_type: "newsletter"}, instance_ids: ["inst-p6"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 2, upstream: [{source_id: "src-wire", relation_type: "repeats", fidelity: "faithful"}], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-post-1", title: "Post: \"runaway inflation\" chart", url: null, source_type: "social_media"}, instance_ids: ["inst-p9"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 3, upstream: [{source_id: "src-oped", relation_type: "repeats", fidelity: "faithful"}], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-post-3", title: "Post: quote of the op-ed", url: null, source_type: "social_media"}, instance_ids: ["inst-p11"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 3, upstream: [{source_id: "src-oped", relation_type: "repeats", fidelity: "faithful"}], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-post-2", title: "Post: thread on 2022 prices", url: null, source_type: "social_media"}, instance_ids: ["inst-p10"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 3, upstream: [{source_id: "src-oped", relation_type: "repeats", fidelity: "faithful"}], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-post-4", title: "Post: video clip caption", url: null, source_type: "social_media"}, instance_ids: ["inst-p12"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 3, upstream: [{source_id: "src-oped", relation_type: "repeats", fidelity: "faithful"}], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
    {source: {id: "src-check", title: "Was 2022 inflation \"runaway\"? A fact-check", url: null, source_type: "fact_check"}, instance_ids: ["inst-p13"], underlying: false, standing: "derived", basis: "upstream", root: null, depth: 3, upstream: [{source_id: "src-oped", relation_type: "responds_to", fidelity: "faithful"}], copy_of: [], downstream: 0, downstream_total: 0, copies: 0, diverges: false},
  ],
  counts: {sources: 20, origins: 2, untraced: 2, derived: 16, underlying: 1},
};
