import Anthropic from "@anthropic-ai/sdk";

type MessageParam = Anthropic.MessageParam;
type ContentBlock = Anthropic.ContentBlock;
type ToolUseBlock = Anthropic.ToolUseBlock;
type TextBlock = Anthropic.TextBlock;
type ToolUnion = Anthropic.Messages.ToolUnion;
type ToolResultBlockParam = Anthropic.ToolResultBlockParam;
import { loadConfig } from "../config.js";
import { checkBudget, recordUsage } from "./budget-tracker.js";
import { LlmRefusalError } from "./errors.js";
import {
  DEFAULT_MODEL,
  MODELS,
  modelAcceptsTemperature,
  modelNeedsRefusalFallback,
} from "./models.js";
import { meterLlmUsage } from "../services/usage-service.js";

/**
 * Record one call against both meters: the in-memory budget tracker (process
 * circuit breaker) and the durable per-user meter (#70). The durable write is
 * fire-and-forget and swallows its own errors — metering must never fail a
 * call — while attribution (user/key/agent) rides in via the ambient usage
 * context (see usage-context.ts).
 */
function recordCallUsage(model: string, u: Anthropic.Usage): void {
  const cacheRead = u.cache_read_input_tokens ?? 0;
  const cacheCreation = u.cache_creation_input_tokens ?? 0;
  recordUsage(u.input_tokens, u.output_tokens, {
    readTokens: cacheRead,
    creationTokens: cacheCreation,
  });
  void meterLlmUsage({
    model,
    inputTokens: u.input_tokens,
    outputTokens: u.output_tokens,
    cacheReadTokens: cacheRead,
    cacheCreationTokens: cacheCreation,
  });
}

/** Build the optional `temperature` field, omitting it for models that reject it. */
function temperatureParam(model: string, temperature?: number): { temperature?: number } {
  if (!modelAcceptsTemperature(model)) return {};
  return { temperature: temperature ?? 0 };
}

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
}

export interface ToolUse {
  id: string;
  name: string;
  input: Record<string, unknown>;
}

export interface CompletionResult {
  content: string;
  model: string;
  usage: TokenUsage;
  stopReason: string | null;
  /**
   * Container id when the request used a container-backed server tool (the
   * `web_search_20260209` tool runs via code execution in a container). It MUST
   * be threaded back into subsequent requests of the same multi-turn loop, or
   * the API 400s with "container_id is required when there are pending tool uses
   * generated by code execution with tools".
   */
  container?: string | null;
}

export interface ToolCompletionResult extends CompletionResult {
  toolUses: ToolUse[];
  rawContent: ContentBlock[];
}

let _client: Anthropic | null = null;

function getClient(): Anthropic {
  if (_client) return _client;
  const config = loadConfig();
  // Bound how long a single request can stall. The SDK default is 10 minutes,
  // so one wedged socket can freeze an entire ingestion run; cap it (override
  // with LLM_REQUEST_TIMEOUT_MS) and let the SDK's automatic retries recover.
  const timeout = Number(process.env.LLM_REQUEST_TIMEOUT_MS ?? 180_000);
  const maxRetries = Number(process.env.LLM_MAX_RETRIES ?? 4);
  _client = new Anthropic({ apiKey: config.anthropicApiKey, timeout, maxRetries });
  return _client;
}

// --- Prompt caching --------------------------------------------------------
// The system prompt (constitution + role, several KB and identical across every
// call to a given agent) and the tool schemas are a large, stable prefix. We
// mark them with ephemeral cache_control so repeated calls within the ~5 min
// window reuse the cached prefix — a big cost/latency win in a full corpus run
// (one system prompt, hundreds of claims) and in production. See
// https://platform.claude.com/docs/en/build-with-claude/prompt-caching

/** Print cache hit/miss tokens when LLM_LOG_CACHE is set (verification aid). */
function logCacheUsage(u: Anthropic.Usage): void {
  if (!process.env.LLM_LOG_CACHE) return;
  console.error(
    `[cache] read=${u.cache_read_input_tokens ?? 0} ` +
      `created=${u.cache_creation_input_tokens ?? 0} ` +
      `input=${u.input_tokens} output=${u.output_tokens}`
  );
}

/** Turn a string system prompt into a single cached text block. */
function cachedSystem(
  system: string | undefined
): string | Anthropic.TextBlockParam[] | undefined {
  if (!system) return undefined;
  return [
    { type: "text", text: system, cache_control: { type: "ephemeral" } },
  ];
}

/**
 * Mark the tool list as cacheable by putting cache_control on the LAST tool
 * (the breakpoint caches every preceding tool too). Returns a new array.
 */
function cachedTools(tools: ToolUnion[]): ToolUnion[] {
  if (tools.length === 0) return tools;
  const out = tools.slice();
  const last = out[out.length - 1]!;
  out[out.length - 1] = {
    ...last,
    cache_control: { type: "ephemeral" },
  } as ToolUnion;
  return out;
}

// DEFAULT_MODEL (Claude Sonnet 5) lives in ./models.ts — the single source of
// truth for model IDs.

/**
 * Create one message, routing Fable-family models through the beta endpoint
 * with the server-side Opus fallback: their safety classifiers can decline a
 * benign-adjacent request (HTTP 200, stop_reason "refusal"), and the fallback
 * re-serves it on Opus 4.8 inside the same call instead of failing the agent
 * run. Other models use the plain Messages endpoint unchanged.
 *
 * The beta response/params are structural supersets of the non-beta types for
 * everything this client reads (content, usage, stop_reason, container), so
 * the casts below keep the beta surface contained to this one function.
 */
async function createMessage(
  params: Anthropic.MessageCreateParamsNonStreaming
): Promise<Anthropic.Message> {
  const client = getClient();
  if (modelNeedsRefusalFallback(params.model)) {
    const response = await client.beta.messages.create({
      ...(params as unknown as Anthropic.Beta.Messages.MessageCreateParamsNonStreaming),
      betas: ["server-side-fallback-2026-06-01"],
      fallbacks: [{ model: MODELS.opus }],
    });
    return response as unknown as Anthropic.Message;
  }
  return client.messages.create(params);
}

/**
 * Fail loudly on stop_reason "refusal" instead of returning empty content (or
 * schema-violating output from completeStructured — on a refusal the API does
 * not guarantee the output matches the requested schema, so this must run
 * before any parsing). On Fable models this fires only when the Opus fallback
 * refused too.
 */
function checkRefusal(response: Anthropic.Message, model: string): void {
  if (response.stop_reason === "refusal") {
    throw new LlmRefusalError(model, response.stop_details?.category ?? null);
  }
}

export async function complete(options: {
  messages: MessageParam[];
  system?: string;
  model?: string;
  maxTokens?: number;
  temperature?: number;
  tools?: ToolUnion[];
  container?: string;
}): Promise<CompletionResult> {
  checkBudget();

  const model = options.model ?? DEFAULT_MODEL;

  // Sonnet 5 runs adaptive thinking by default and thinking spend counts
  // against max_tokens, so the old 4096 default left too little room for the
  // actual answer — 8192 keeps headroom without changing agent call sites.
  const response = await createMessage({
    model,
    messages: options.messages,
    max_tokens: options.maxTokens ?? 8192,
    ...temperatureParam(model, options.temperature),
    ...(options.system ? { system: cachedSystem(options.system) } : {}),
    ...(options.tools ? { tools: cachedTools(options.tools) } : {}),
    ...(options.container ? { container: options.container } : {}),
  });
  checkRefusal(response, model);

  const usage: TokenUsage = {
    inputTokens: response.usage.input_tokens,
    outputTokens: response.usage.output_tokens,
  };

  recordCallUsage(response.model ?? model, response.usage);
  logCacheUsage(response.usage);

  let content = "";
  for (const block of response.content) {
    if (block.type === "text") {
      content += (block as TextBlock).text;
    }
  }

  return {
    content,
    model,
    usage,
    stopReason: response.stop_reason,
    container: response.container?.id ?? null,
  };
}

export async function completeWithTools(options: {
  messages: MessageParam[];
  tools: ToolUnion[];
  system?: string;
  model?: string;
  maxTokens?: number;
  temperature?: number;
  container?: string;
}): Promise<ToolCompletionResult> {
  checkBudget();

  const model = options.model ?? DEFAULT_MODEL;

  const response = await createMessage({
    model,
    messages: options.messages,
    max_tokens: options.maxTokens ?? 8192,
    ...temperatureParam(model, options.temperature),
    tools: cachedTools(options.tools),
    ...(options.system ? { system: cachedSystem(options.system) } : {}),
    ...(options.container ? { container: options.container } : {}),
  });
  checkRefusal(response, model);

  const usage: TokenUsage = {
    inputTokens: response.usage.input_tokens,
    outputTokens: response.usage.output_tokens,
  };

  recordCallUsage(response.model ?? model, response.usage);
  logCacheUsage(response.usage);

  let textContent = "";
  const toolUses: ToolUse[] = [];

  for (const block of response.content) {
    if (block.type === "text") {
      textContent += (block as TextBlock).text;
    } else if (block.type === "tool_use") {
      const tb = block as ToolUseBlock;
      toolUses.push({
        id: tb.id,
        name: tb.name,
        input: tb.input as Record<string, unknown>,
      });
    }
  }

  return {
    content: textContent,
    model,
    usage,
    stopReason: response.stop_reason,
    toolUses,
    rawContent: response.content,
    container: response.container?.id ?? null,
  };
}

/**
 * Get a structured response via the API's native structured outputs
 * (`output_config.format`): the API constrains generation to the schema and
 * returns the JSON as text content, which we parse and return.
 *
 * Schema restrictions apply (a strict JSON Schema subset): every object must
 * set `additionalProperties: false` with a complete `required` array; numeric
 * bounds (minimum/maximum), string length constraints, and recursive schemas
 * are not supported — validate those in code instead. The first request with a
 * new schema pays a one-time server-side compilation cost; compiled schemas
 * are cached for 24 hours.
 */
export async function completeStructured<T>(options: {
  messages: MessageParam[];
  schema: Record<string, unknown>;
  schemaName: string;
  system?: string;
  model?: string;
  maxTokens?: number;
  temperature?: number;
}): Promise<T> {
  checkBudget();

  const model = options.model ?? DEFAULT_MODEL;
  const maxTokens = options.maxTokens ?? 8192;

  // No tools on this request — the system prompt block from cachedSystem is
  // the sole cache breakpoint, and its cache_control applies regardless.
  const response = await createMessage({
    model,
    messages: options.messages,
    max_tokens: maxTokens,
    ...temperatureParam(model, options.temperature),
    ...(options.system ? { system: cachedSystem(options.system) } : {}),
    output_config: {
      format: { type: "json_schema", schema: options.schema },
    },
  });
  // On a refusal the output is not guaranteed to match the schema — fail
  // loudly before attempting to parse.
  checkRefusal(response, model);

  recordCallUsage(response.model ?? model, response.usage);
  logCacheUsage(response.usage);

  // The structured response arrives as JSON text in the text content block(s).
  let text = "";
  for (const block of response.content) {
    if (block.type === "text") {
      text += (block as TextBlock).text;
    }
  }

  if (response.stop_reason === "max_tokens") {
    // Truncated output is invalid/incomplete JSON (this bites on large inputs —
    // a 9k-word document once overflowed the extractor). Fail with an
    // actionable message instead of a bare JSON parse error.
    throw new Error(
      `Structured response "${options.schemaName}" was truncated at ` +
        `max_tokens (${maxTokens}) and cannot be parsed. Increase maxTokens ` +
        `or reduce the input size.`
    );
  }

  try {
    return JSON.parse(text) as T;
  } catch {
    throw new Error(
      `Structured response "${options.schemaName}" was not valid JSON ` +
        `(stop_reason: ${response.stop_reason ?? "unknown"}).`
    );
  }
}

/**
 * Get a structured list response by wrapping the item schema in an
 * `{ items: [...] }` object (structured outputs require a top-level object).
 */
export async function completeStructuredList<T>(options: {
  messages: MessageParam[];
  itemSchema: Record<string, unknown>;
  schemaName: string;
  system?: string;
  model?: string;
  maxTokens?: number;
  temperature?: number;
}): Promise<T[]> {
  const wrapperSchema = {
    type: "object" as const,
    properties: {
      items: {
        type: "array",
        items: options.itemSchema,
      },
    },
    required: ["items"],
    additionalProperties: false,
  };

  const result = await completeStructured<{ items: T[] }>({
    messages: options.messages,
    schema: wrapperSchema,
    schemaName: `ListOf${options.schemaName}`,
    system: options.system,
    model: options.model,
    maxTokens: options.maxTokens,
    temperature: options.temperature,
  });

  if (!Array.isArray(result?.items)) {
    // Defensive: completeStructured already throws on max_tokens truncation
    // and on unparseable JSON, but fail with an actionable message here too
    // rather than a downstream "x is not iterable".
    throw new Error(
      `Structured list "${options.schemaName}" returned no items array — the ` +
        `response was likely truncated at max_tokens (${options.maxTokens ?? 8192}). ` +
        `Increase maxTokens or reduce the input size.`
    );
  }

  return result.items;
}

/**
 * Run a multi-turn tool-use loop. Calls the model, executes tools, feeds results back.
 * Continues until the model stops calling tools or maxIterations is reached.
 */
export async function toolUseLoop(options: {
  initialMessages: MessageParam[];
  tools: ToolUnion[];
  system?: string;
  model?: string;
  maxTokens?: number;
  temperature?: number;
  maxIterations?: number;
  executeTool: (name: string, input: Record<string, unknown>) => Promise<string>;
  /** Called when the model calls a "final" tool (e.g. submit_decomposition). Return result to stop loop. */
  onFinalTool?: (name: string, input: Record<string, unknown>) => unknown | null;
  /**
   * When set, the loop appends a plain-text budget notice to the tool-result
   * message once only `warnWithin` iterations remain, so the agent can finish
   * its essential actions (e.g. recording an assessment) instead of being cut
   * off mid-task at maxIterations. The string is the agent-facing wording.
   */
  iterationBudgetNotice?: { warnWithin: number; message: (remaining: number) => string };
}): Promise<ToolCompletionResult> {
  const messages = [...options.initialMessages];
  const maxIter = options.maxIterations ?? 5;
  let lastResult: ToolCompletionResult | null = null;
  // Container-backed server tools (web_search_20260209 runs via code execution)
  // mint a container on first use that MUST be passed back on every later turn of
  // the loop, or the API rejects the request. Thread the latest id through.
  let containerId: string | undefined;

  for (let i = 0; i < maxIter; i++) {
    const result = await completeWithTools({
      messages,
      tools: options.tools,
      system: options.system,
      model: options.model,
      maxTokens: options.maxTokens,
      temperature: options.temperature,
      container: containerId,
    });

    lastResult = result;
    if (result.container) containerId = result.container;

    // A long-running server tool (e.g. web_search) can pause the turn. The
    // documented continuation is to resubmit the assistant content UNCHANGED and
    // call again — NOT to inject tool results. Doing the latter (or doing nothing)
    // strands a pending server_tool_use and the next request 400s with
    // "container_id is required when there are pending tool uses…".
    if (result.stopReason === "pause_turn") {
      messages.push({ role: "assistant", content: result.rawContent });
      continue;
    }

    // A turn truncated at max_tokens can leave a server tool use (web search)
    // half-emitted. Resubmitting that turn triggers the same 400, which would
    // crash the whole agent run and lose its work. Stop gracefully with the
    // best-effort result instead — the caller (e.g. the Steward) has already
    // been told to record its conclusion before the budget runs out.
    if (result.stopReason === "max_tokens") {
      return result;
    }

    if (result.stopReason === "end_turn" || result.toolUses.length === 0) {
      return result;
    }

    // Check for final tool
    if (options.onFinalTool) {
      for (const tu of result.toolUses) {
        const finalResult = options.onFinalTool(tu.name, tu.input);
        if (finalResult !== null && finalResult !== undefined) {
          return result;
        }
      }
    }

    // Execute tools and build tool_result messages
    const toolResults: ToolResultBlockParam[] = [];
    for (const tu of result.toolUses) {
      const output = await options.executeTool(tu.name, tu.input);
      toolResults.push({
        type: "tool_result",
        tool_use_id: tu.id,
        content: output,
      });
    }

    // If the iteration budget is nearly spent, tell the agent so it can wrap up
    // its essential actions on the next turn rather than being hard-cut.
    const remaining = maxIter - 1 - i;
    const notice = options.iterationBudgetNotice;
    const userContent: Array<ToolResultBlockParam | { type: "text"; text: string }> = [
      ...toolResults,
    ];
    if (notice && remaining > 0 && remaining <= notice.warnWithin) {
      userContent.push({ type: "text", text: notice.message(remaining) });
    }

    // Append assistant message and tool results
    messages.push({ role: "assistant", content: result.rawContent });
    messages.push({ role: "user", content: userContent });
  }

  return lastResult!;
}
