/**
 * Shared types for the multi-provider LLM seam.
 *
 * The public seam (src/llm/client.ts) speaks ONE dialect: Anthropic's
 * `MessageParam` / `ToolUnion` shapes. That is deliberate — every agent in
 * src/llm/agents/ is written against it, and switching an agent to another
 * provider must be a single env var, never a code change. Each adapter is
 * responsible for translating that dialect into its own platform's native wire
 * format and back (see providers/openai-dialect.ts for the OpenAI-compatible
 * translation shared by the OpenAI and OpenRouter adapters).
 */
import type Anthropic from "@anthropic-ai/sdk";

/** A conversation message, in the seam's Anthropic dialect. */
export type LlmMessage = Anthropic.MessageParam;
/** A tool definition, in the seam's Anthropic dialect (client OR server tool). */
export type LlmTool = Anthropic.Messages.ToolUnion;
/** An assistant-turn content block, in the seam's Anthropic dialect. */
export type LlmContentBlock = Anthropic.ContentBlock;

/** The three backends behind the seam. */
export type ProviderName = "anthropic" | "openai" | "openrouter";

export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
}

export interface ToolUse {
  id: string;
  name: string;
  input: Record<string, unknown>;
}

export interface CompletionResult {
  content: string;
  model: string;
  usage: TokenUsage;
  stopReason: string | null;
  /**
   * Container id when the request used a container-backed server tool (the
   * `web_search_20260209` tool runs via code execution in a container). It MUST
   * be threaded back into subsequent requests of the same multi-turn loop, or
   * the API 400s with "container_id is required when there are pending tool uses
   * generated by code execution with tools".
   *
   * Anthropic-only — the other adapters reject `container` outright.
   */
  container?: string | null;
}

export interface ToolCompletionResult extends CompletionResult {
  toolUses: ToolUse[];
  /**
   * The assistant turn, re-expressed as Anthropic content blocks. It only ever
   * round-trips back through toolUseLoop's message append, so an adapter is
   * free to synthesize whatever blocks let IT reconstruct the turn on the next
   * request — no agent reads this.
   */
  rawContent: LlmContentBlock[];
}

export interface CompleteRequest {
  messages: LlmMessage[];
  model: string;
  maxTokens: number;
  system?: string;
  temperature?: number;
  tools?: LlmTool[];
  container?: string;
}

export interface ToolCompleteRequest extends CompleteRequest {
  tools: LlmTool[];
}

export interface StructuredRequest {
  messages: LlmMessage[];
  schema: Record<string, unknown>;
  schemaName: string;
  model: string;
  maxTokens: number;
  system?: string;
  temperature?: number;
}

/**
 * One backend. Adding a capability to one adapter must never touch another:
 * this interface is the ONLY thing client.ts knows about a provider, and each
 * implementation speaks its own platform's native dialect underneath.
 */
export interface ProviderAdapter {
  readonly name: ProviderName;
  complete(req: CompleteRequest): Promise<CompletionResult>;
  completeWithTools(req: ToolCompleteRequest): Promise<ToolCompletionResult>;
  completeStructured<T>(req: StructuredRequest): Promise<T>;
}
