/**
 * Shared types for the multi-provider LLM seam.
 *
 * The public seam (src/llm/client.ts) speaks ONE dialect: Anthropic's
 * `MessageParam` / `ToolUnion` shapes. That is deliberate — every agent in
 * src/llm/agents/ is written against it, and switching an agent to another
 * provider must be a single env var, never a code change. Each adapter is
 * responsible for translating that dialect into its own platform's native wire
 * format and back (see providers/responses-dialect.ts for OpenAI's Responses
 * translation and providers/openai-dialect.ts for OpenRouter's Chat
 * Completions one, plus the helpers both share).
 */
import type Anthropic from "@anthropic-ai/sdk";

/** A conversation message, in the seam's Anthropic dialect. */
export type LlmMessage = Anthropic.MessageParam;
/** A tool definition, in the seam's Anthropic dialect (client OR server tool). */
export type LlmTool = Anthropic.Messages.ToolUnion;
/** An assistant-turn content block, in the seam's Anthropic dialect. */
export type LlmContentBlock = Anthropic.ContentBlock;

/** The three backends behind the seam. */
export type ProviderName = "anthropic" | "openai" | "openrouter";

export interface TokenUsage {
  /** Uncached input tokens (cache reads and writes are reported separately). */
  inputTokens: number;
  outputTokens: number;
  /** Input tokens served from the prompt cache. Set by the Anthropic adapter. */
  cacheReadTokens?: number;
  /** Input tokens written to the prompt cache. Set by the Anthropic adapter. */
  cacheCreationTokens?: number;
}

/** Reasoning depth, sent as `output_config.effort` on Anthropic requests. */
export type EffortLevel = "low" | "medium" | "high" | "xhigh" | "max";

/**
 * A system prompt: one string, or several blocks in order (constitution plus
 * role, then domain skills). The Anthropic adapter caches each block
 * separately so a skill appended after the role block leaves the role block's
 * cache entry shared with unskilled runs; the other adapters join the blocks
 * into the single system field their APIs have.
 */
export type SystemPrompt = string | string[];

export interface ToolUse {
  id: string;
  name: string;
  input: Record<string, unknown>;
}

export interface CompletionResult {
  content: string;
  model: string;
  usage: TokenUsage;
  stopReason: string | null;
  /**
   * Container id when the request used a container-backed server tool (the
   * `web_search_20260209` tool runs via code execution in a container). It MUST
   * be threaded back into subsequent requests of the same multi-turn loop, or
   * the API 400s with "container_id is required when there are pending tool uses
   * generated by code execution with tools".
   *
   * Anthropic-only — the other adapters reject `container` outright.
   */
  container?: string | null;
}

export interface ToolCompletionResult extends CompletionResult {
  toolUses: ToolUse[];
  /**
   * The assistant turn, re-expressed as Anthropic content blocks. It only ever
   * round-trips back through toolUseLoop's message append, so an adapter is
   * free to synthesize whatever blocks let IT reconstruct the turn on the next
   * request — no agent reads this.
   */
  rawContent: LlmContentBlock[];
  /**
   * The model that actually produced the turn (`response.model`). Differs from
   * `model` when a server-side refusal fallback re-served the request on
   * another model; a fallback is sticky for about an hour, so later turns can
   * carry it without a fallback block. Anthropic-only.
   */
  servedModel?: string;
  /** True when `servedModel` differs from the requested model. Anthropic-only. */
  fallbackRan?: boolean;
}

export interface CompleteRequest {
  messages: LlmMessage[];
  model: string;
  maxTokens: number;
  system?: SystemPrompt;
  temperature?: number;
  tools?: LlmTool[];
  container?: string;
  /** Anthropic `output_config.effort`; the other adapters ignore it. */
  effort?: EffortLevel;
}

export interface ToolCompleteRequest extends CompleteRequest {
  tools: LlmTool[];
}

export interface StructuredRequest {
  messages: LlmMessage[];
  schema: Record<string, unknown>;
  schemaName: string;
  model: string;
  maxTokens: number;
  system?: SystemPrompt;
  temperature?: number;
  /** Anthropic `output_config.effort`; the other adapters ignore it. */
  effort?: EffortLevel;
}

/**
 * One turn of a long-running agent loop (client.ts longRunToolLoop). Served by
 * the Anthropic adapter's streaming path only: streaming is what lets a turn
 * run to 128K output tokens without an HTTP timeout, and the betas below have
 * no equivalent elsewhere.
 */
export interface LongRunRequest extends ToolCompleteRequest {
  effort?: EffortLevel;
  /**
   * Advisory token budget for the whole task (`output_config.task_budget`), so
   * the model paces itself instead of being cut off. Minimum 20,000.
   */
  taskBudgetTokens?: number;
  /**
   * "server" opts into the server-side refusal fallback (the request is
   * re-served on the Opus tier inside the same call when the model's safety
   * classifiers decline); "none" lets a refusal surface as LlmRefusalError.
   */
  fallbacks: "none" | "server";
  /** Extra `anthropic-beta` ids to send verbatim. */
  betas?: string[];
}

/**
 * One backend. Adding a capability to one adapter must never touch another:
 * this interface is the ONLY thing client.ts knows about a provider, and each
 * implementation speaks its own platform's native dialect underneath.
 */
export interface ProviderAdapter {
  readonly name: ProviderName;
  complete(req: CompleteRequest): Promise<CompletionResult>;
  completeWithTools(req: ToolCompleteRequest): Promise<ToolCompletionResult>;
  completeStructured<T>(req: StructuredRequest): Promise<T>;
  /**
   * The long-run path: a streamed tool turn with the long-run betas. Optional
   * because only the Anthropic adapter has it; client.ts fails with a
   * capability message when the routed adapter lacks it, the way the other
   * adapters reject server tools today.
   */
  completeWithToolsStreaming?(req: LongRunRequest): Promise<ToolCompletionResult>;
}
